### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by RobertAudi** [ConradIrwin/console.log#1]
Really cool project! Can't believe nobody thought about that before... :+1:

It would be really cool if there was some aliases though:
- `cl`: `console.log`
- `cw`: `console.warn`
- `ce`: `console.error`

I just checked, and all of these are available / not taken.

Other potentially cool features:
- A `pc` (i.e.: `puts_console`, maybe?) alias could be nice, with a configuration that could be set to specify the default importance of the output (log, warn or error).
- Custom serializers

**Comment by ConradIrwin** [comment]
Thanks @RobertAudi! I don't really want to pollute everyone's global namespace with two-letter functions. Luckily in most editors it's easy to set up keyboard shortcuts to do exactly what you want :). (Or you could add `config/initializers/console.log.rb` with:

``` ruby
def cl(*a); console.log(*A); end
...
```

I'm not sure I get the idea behind `puts_console`? Logging to `console.log` is puts'd by default.
